// Generated by CoffeeScript 1.6.3
var ParticleBase;

ParticleBase = (function() {
  ParticleBase.obj = null;

  function ParticleBase(obj) {
    this.obj = obj;
  }

  return ParticleBase;

})();

/*
//@ sourceMappingURL=ParticleBase.map
*/
