// Generated by CoffeeScript 1.6.3
var ParticleCircle,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ParticleCircle = (function(_super) {
  __extends(ParticleCircle, _super);

  function ParticleCircle() {
    ParticleCircle.__super__.constructor.call(this);
  }

  return ParticleCircle;

})(ParticleBase);

/*
//@ sourceMappingURL=ParticleCircle.map
*/
