// Generated by CoffeeScript 1.6.3
var PConfig;

PConfig = (function() {
  function PConfig() {}

  PConfig.stage = null;

  PConfig.stageW = 600;

  PConfig.stageH = 400;

  return PConfig;

})();

/*
//@ sourceMappingURL=PConfig.map
*/
